<?php
    $this->headTitle()->prepend('Datagraph | ');
?>

<section id="datagraph-section">

    <h1>Datagraph</h1>
    
    <a href="<?=$this->url(array('controller'=>'dataset', 'action'=>'updateparkings'), null, true)?>" class="btn btn-default" title="Update Parkings">Update Parkings</a>
    <a href="<?=$this->url(array('controller'=>'dataset', 'action'=>'updatestations'), null, true)?>" class="btn btn-default" title="Update Stations">Update Stations</a>
    <a href="<?=$this->url(array('controller'=>'dataset', 'action'=>'updatebioscopen'), null, true)?>" class="btn btn-default" title="Update Bioscopen">Update Bioscopen</a>
    <a href="<?=$this->url(array('controller'=>'dataset', 'action'=>'updatebibliotheken'), null, true)?>" class="btn btn-default" title="Update Bibliotheken">Update Bibliotheken</a>
    <a href="<?=$this->url(array('controller'=>'dataset', 'action'=>'updatebasisscholen'), null, true)?>" class="btn btn-default" title="Update Basisscholen">Update Basisscholen</a>
    <a href="<?=$this->url(array('controller'=>'dataset', 'action'=>'updatesecundairescholen'), null, true)?>" class="btn btn-default" title="Update Secundaire Scholen">Update Secundaire Scholen</a>
    <a href="<?=$this->url(array('controller'=>'dataset', 'action'=>'updateziekenhuizen'), null, true)?>" class="btn btn-default" title="Update Ziekenhuizen">Update Ziekenhuizen</a>
    <a href="<?=$this->url(array('controller'=>'dataset', 'action'=>'updateapotheken'), null, true)?>" class="btn btn-default" title="Update Apotheken">Update Apotheken</a>
    <a href="<?=$this->url(array('controller'=>'dataset', 'action'=>'updatedierenartsen'), null, true)?>" class="btn btn-default" title="Update Dierenartsen">Update Dierenartsen</a>
    <a href="<?=$this->url(array('controller'=>'dataset', 'action'=>'updatehuisartsen'), null, true)?>" class="btn btn-default" title="Update Huisartsen">Update Huisartsen</a>
    
</section>
