<?php
    $this->headTitle()->prepend('Home | ');
?>

<section class="content-home">
    <div id="map-controls">
        <h1>Spot locaties in Gent</h1>
        
        <ul class="list-unstyled">
            <li><a href="#" id="stations" title="Stations" class="btn btn-default" onclick="locate(this.id)">Stations</a></li>
            <li><a href="#" id="parkings" title="Parkeerplaatsen" class="btn btn-default" onclick="locate(this.id)">Parkeerplaatsen</a></li>
            <li><a href="#" id="bioscopen" title="Bioscopen" class="btn btn-default" onclick="locate(this.id)">Bioscopen</a></li>
            <li><a href="#" id="bibliotheken" title="Bibliotheken" class="btn btn-default" onclick="locate(this.id)">Bibliotheken</a></li>
            <li><a href="#" id="basisscholen" title="Basisscholen" class="btn btn-default" onclick="locate(this.id)">Basisscholen</a></li>
            <li><a href="#" id="secundairescholen" title="Secundaire Scholen" class="btn btn-default" onclick="locate(this.id)">Secundaire Scholen</a></li>
            <li><a href="#" id="apotheken" title="Apotheken" class="btn btn-default" onclick="locate(this.id)">Apotheken</a></li>
            <li><a href="#" id="huisartsen" title="Huisartsen" class="btn btn-default" onclick="locate(this.id)">Huisartsen</a></li>
            <li><a href="#" id="ziekenhuizen" title="Ziekenhuizen" class="btn btn-default" onclick="locate(this.id)">Ziekenhuizen</a></li>
            <li><a href="#" id="dierenartsen" title="Dierenartsen" class="btn btn-default" onclick="locate(this.id)">Dierenartsen</a></li>
        </ul>
    </div>

    <div id="map-canvas">

    </div>
</section>