<?php
    $this->headTitle()->prepend('Home | ');
?>

<section class="content-home">
    <div id="map-controls">
        <h1>Spot locaties in Gent</h1>
        
        <ul class="list-unstyled">
            <li><a href="#" title="Stations" class="btn btn-default">Stations</a></li>
            <li><a href="#" title="Parkeerplaatsen" class="btn btn-default" onclick="locateParkings()">Parkeerplaatsen</a></li>
            <li><a href="#" title="Bioscopen" class="btn btn-default">Bioscopen</a></li>
            <li><a href="#" title="Bibliotheken" class="btn btn-default">Bibliotheken</a></li>
            <li><a href="#" title="Basisscholen" class="btn btn-default">Basisscholen</a></li>
            <li><a href="#" title="Secundaire Scholen" class="btn btn-default">Secundaire Scholen</a></li>
            <li><a href="#" title="Apotheken" class="btn btn-default">Apotheken</a></li>
            <li><a href="#" title="Huisartsen" class="btn btn-default">Huisartsen</a></li>
            <li><a href="#" title="Ziekenhuizen" class="btn btn-default">Ziekenhuizen</a></li>
            <li><a href="#" title="Dierenartsen" class="btn btn-default">Dierenartsen</a></li>
        </ul>
    </div>

    <div id="map-canvas">

    </div>
</section>