<?php
    $this->headTitle()->prepend('Home | ');
?>

<section class="content-home">
    <div id="map-controls">
        <h1>Spot locaties in Gent</h1>
        
        <ul class="unstyled">
            <li><a href="#" title="Stations" class="btn">Stations</a></li>
            <li><a href="#" title="Parkeerplaatsen" class="btn">Parkeerplaatsen</a></li>
            <li><a href="#" title="Bioscopen" class="btn">Bioscopen</a></li>
            <li><a href="#" title="Bibliotheken" class="btn">Bibliotheken</a></li>
            <li><a href="#" title="Basisscholen" class="btn">Basisscholen</a></li>
        </ul>
        <ul class="unstyled">
            <li><a href="#" title="Secundaire Scholen" class="btn">Secundaire Scholen</a></li>
            <li><a href="#" title="Apotheken" class="btn">Apotheken</a></li>
            <li><a href="#" title="Huisartsen" class="btn">Huisartsen</a></li>
            <li><a href="#" title="Ziekenhuizen" class="btn">Ziekenhuizen</a></li>
            <li><a href="#" title="Dierenartsen" class="btn">Dierenartsen</a></li>
        </ul>
    </div>

    <div id="map-canvas">

    </div>
</section>