<?php
    $this->headTitle()->prepend('Over | ');
?>
<section id="about-content">
    <img src="http://placehold.it/600x350">
    <h1>Over Deze Webapplicatie</h1>
    <p>Deze applicatie wordt voorgedragen door Dieter Nonneman tot het behalen van het diploma Bachelor in Grafische en Digitale Media, Multimediaproductie ProDEV.</p>
    <p>
        Dataspot Ghent heeft als doel om het voor de gebruiker gemakkelijk te maken om wegwijs te geraken in de stad Gent.
        Hiertoe is er een beperkt aantal datasets gebruikt, beschikbaar gesteld door 
        <a href="http://data.gent.be/" title="Open data portaal Stad Gent">Open Data Gent</a> en 
        <a href="http://appsforghent.be/" title="Apps For Ghent">Apps For Ghent</a>. 
    </p>
    <p>
        Deze webapplicatie werd ontwikkeld met Zend Framework, jQuery Mobile, Less CSS, HTML 5, CSS3, Javascript, Twitter Bootstrap en PHP 5.4.4.
    </p>
    
</section>