<header data-role="header">
                
    <a id="logo" href="<?=$this->url(array('controller'=>'index', 'action'=>'index'), null, true)?>"><img src="<?=$this->baseUrl('images/logo.png')?>" alt="Dataspot Ghent" /></a>

    
    <a href="#popupBasic" data-rel="popup" id="popup-login">
        <?php 
            $auth = Zend_Auth::getInstance(); 
            if($auth->getIdentity())
            {
                echo 'Welkom | Beheer';
            } else 
            {
                echo 'Inloggen | Registreren';
            } 
        ?>
    </a>
    <div class="login-widget" id="popupBasic">
        <a href="#" data-rel="back" data-role="button" data-theme="a" data-icon="delete" data-iconpos="notext" class="ui-btn-right">Close</a>
        
        <?php echo $this->loggedIn();?>

        <a class="login-register-btn" data-role="button" title="Registreer Nu" href="<?=$this->url(array('controller'=>'auth', 'action'=>'register'), null, true)?>">Registreren</a>

        <!-- Error message when wrong password -->
        <?php if($this->errorMessage != ""): ?>  
            <p class="login-fail text-right"><?= $this->errorMessage; ?></p>  
        <?php endif; ?>

    </div>

    <nav data-role="navbar">

        <a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
            Navigatie
            <span class="caret"></span>
        </a>
        <p>Spot nu de meest interessante locaties in Gent.</p>
        <?php echo $this->navigation()->menu(); ?>

    </nav>

</header>